[build]
command   = "npm install && echo \"window.__STRIPE_KEY__='${STRIPE_KEY}';window.__ANTHROPIC_KEY__='${ANTHROPIC_KEY}';window.__FIREBASE_API_KEY__='${FIREBASE_API_KEY}';window.__EMAILJS_SERVICE__='${EMAILJS_SERVICE}';window.__EMAILJS_TEMPLATE__='${EMAILJS_TEMPLATE}';window.__EMAILJS_KEY__='${EMAILJS_KEY}';window.__ADMIN_UID__='${ADMIN_UID}';\" > public/config.js && npm run build"
  publish   = "public"
